# Bot API
TOKEN = "5898247314:AAF10jDzxJFERS9fOnrm5dqj1qCaOz8w4hM"

# DB Server
host = "80.90.184.159"
username = "gen_user"
password = "400044911Vm"
database = "default_db"


# PIPELINE 1 - MAIN
# PIPELINE 2 - LANGUAGE
# PIPELINE 3 - COMMENT
# PIPELINE 4 - MY PROFILE
# PIPELINE 5 - EDIT NAME, PHONE AND ADDRESS 
# PIPELINE 6 - CATEGORY LIST
# PIPELINE 7 - PRODUCT LIST
# PIPELINE 8 - PRODUCT INFO
# PIPELINE 9 - CART
# PIPELINE 10 - START OFORMIT ORDER
# PIPELINE 11 - OPLATA ORDER