# Bot API
TOKEN = "TOKEN"

# DB Server
host = "host"
username = "user"
password = "password"
database = "dtabase_name"


# PIPELINE 1 - MAIN
# PIPELINE 2 - LANGUAGE
# PIPELINE 3 - COMMENT
# PIPELINE 4 - MY PROFILE
# PIPELINE 5 - EDIT NAME, PHONE AND ADDRESS 
# PIPELINE 6 - CATEGORY LIST
# PIPELINE 7 - PRODUCT LIST
# PIPELINE 8 - PRODUCT INFO
# PIPELINE 9 - CART
# PIPELINE 10 - START OFORMIT ORDER
# PIPELINE 11 - OPLATA ORDER
